# Generated by Django 5.2.9 on 2026-06-13 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericTokenModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip')),
                ('is_mobile', models.BooleanField(null=True, verbose_name='is mobile')),
                ('is_tablet', models.BooleanField(null=True, verbose_name='is tablet')),
                ('is_pc', models.BooleanField(null=True, verbose_name='is pc')),
                ('is_bot', models.BooleanField(null=True, verbose_name='is bot')),
                ('browser', models.CharField(blank=True, max_length=32, null=True, verbose_name='browser')),
                ('browser_version', models.CharField(blank=True, max_length=32, null=True, verbose_name='browser version')),
                ('os', models.CharField(blank=True, max_length=32, null=True, verbose_name='os')),
                ('os_version', models.CharField(blank=True, max_length=32, null=True, verbose_name='os version')),
                ('device', models.CharField(blank=True, max_length=32, null=True, verbose_name='device')),
                ('device_brand', models.CharField(blank=True, max_length=32, null=True, verbose_name='device brand')),
                ('device_model', models.CharField(blank=True, max_length=32, null=True, verbose_name='device model')),
                ('token', models.CharField(max_length=255, verbose_name='token')),
                ('purpose', models.CharField(max_length=32, verbose_name='purpose')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_tokens', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'refresh token',
                'verbose_name_plural': 'refresh tokens',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RefreshTokenWhitelistModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip')),
                ('is_mobile', models.BooleanField(null=True, verbose_name='is mobile')),
                ('is_tablet', models.BooleanField(null=True, verbose_name='is tablet')),
                ('is_pc', models.BooleanField(null=True, verbose_name='is pc')),
                ('is_bot', models.BooleanField(null=True, verbose_name='is bot')),
                ('browser', models.CharField(blank=True, max_length=32, null=True, verbose_name='browser')),
                ('browser_version', models.CharField(blank=True, max_length=32, null=True, verbose_name='browser version')),
                ('os', models.CharField(blank=True, max_length=32, null=True, verbose_name='os')),
                ('os_version', models.CharField(blank=True, max_length=32, null=True, verbose_name='os version')),
                ('device', models.CharField(blank=True, max_length=32, null=True, verbose_name='device')),
                ('device_brand', models.CharField(blank=True, max_length=32, null=True, verbose_name='device brand')),
                ('device_model', models.CharField(blank=True, max_length=32, null=True, verbose_name='device model')),
                ('jti', models.CharField(max_length=32, verbose_name='jti')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('session', models.CharField(max_length=32, verbose_name='session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens_whitelist', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'refresh token',
                'verbose_name_plural': 'refresh tokens',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
        migrations.CreateModel(
            name='TokenProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('oxi_auth.token',),
        ),
    ]
