# Generated by Django 5.2.9 on 2026-06-13 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxi_auth', '0001_initial'),
        ('oxiliere', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('token', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='token')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin'), ('owner', 'Owner')], default='member', max_length=20, verbose_name='role')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='accepted at')),
                ('resend_count', models.PositiveSmallIntegerField(default=0, verbose_name='resend count')),
                ('message', models.TextField(blank=True, default='', verbose_name='message')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='invited by')),
                ('invitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL, verbose_name='invitee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='oxiliere.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'invitation',
                'verbose_name_plural': 'invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='oxi_auth_in_tenant__670dd2_idx'), models.Index(fields=['email', 'status'], name='oxi_auth_in_email_129cdf_idx')],
            },
        ),
    ]
