# Generated by Django 5.2.9 on 2026-02-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_alter_grant_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='app',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['app'], name='permissions_app_9a9924_idx'),
        ),
    ]
