# Generated by Django 5.2.9 on 2026-02-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_group_app_group_permissions_app_9a9924_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='app',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
