# Generated by Django 5.2.9 on 2026-02-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_role_app'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolegrant',
            options={'ordering': ['role__slug', 'scope']},
        ),
        migrations.RemoveConstraint(
            model_name='rolegrant',
            name='unique_role_scope_group',
        ),
        migrations.RemoveIndex(
            model_name='rolegrant',
            name='permissions_group_i_465f8d_idx',
        ),
        migrations.RemoveIndex(
            model_name='rolegrant',
            name='permissions_role_id_0818de_idx',
        ),
        migrations.RemoveField(
            model_name='rolegrant',
            name='group',
        ),
        migrations.AddIndex(
            model_name='rolegrant',
            index=models.Index(fields=['role', 'scope'], name='permissions_role_id_84ff7d_idx'),
        ),
        migrations.AddConstraint(
            model_name='rolegrant',
            constraint=models.UniqueConstraint(fields=('role', 'scope'), name='unique_role_scope'),
        ),
    ]
