# Generated by Django 5.2.9 on 2026-02-13 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0006_alter_rolegrant_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='locked',
            field=models.BooleanField(default=False, help_text='Si True, ce grant ne sera pas modifié par group_sync'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_grants', to='permissions.role'),
        ),
        migrations.AddIndex(
            model_name='grant',
            index=models.Index(fields=['locked'], name='permissions_locked_99bc12_idx'),
        ),
    ]
