# Generated by Django 5.2.9 on 2026-03-17 23:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0007_grant_locked_alter_grant_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grant',
            name='unique_user_scope_role',
        ),
        migrations.AddConstraint(
            model_name='grant',
            constraint=models.UniqueConstraint(condition=models.Q(('user_group__isnull', False)), fields=('user', 'scope', 'role', 'user_group'), name='unique_user_scope_role_with_group'),
        ),
        migrations.AddConstraint(
            model_name='grant',
            constraint=models.UniqueConstraint(condition=models.Q(('user_group__isnull', True)), fields=('user', 'scope', 'role'), name='unique_user_scope_role_without_group'),
        ),
    ]
