# Generated by Django 5.2.9 on 2026-06-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0008_remove_grant_unique_user_scope_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
